Specify synapse file subset
User can now specify a subset of the parent synapseID to download. Also now using a csv file which contains an updated manifest of synapse project info instead of contacting the synapse server.

diff --git a/SRA_RNASeq_Pipeline b/SRA_RNASeq_Pipeline
--- a/SRA_RNASeq_Pipeline
+++ b/SRA_RNASeq_Pipeline
@@ -11,6 +11,7 @@ function usage {
     echo "SRA_RNASeq_Pipeline [-a SRP_accession] [-p project_directory] [-t tests] [-g genome_directory] [-P num_threads] "
     echo
     echo "  -a|--SRP_accession     SRP       SRA study accession to download data from. [e.g. SRP045672]."
+    echo "  -l|--SRA_list          file      File with newline-separated list of SRP, SRX, and/or SRR accessions."
     echo "  -p|--project_dir       dir       Name of project directory. [default = 'RNASeq_SRA_Pipeline_Project']"
     echo "  -t|--tests             string    's' [salmon] 't' [TECount] 'S' [Splicing-STAR] 'f' [STAR-Fusion] Default: 'stSf'"
     echo "  -g|--genome_dir        dir       Name of genome directory. [default = package_dir/genome_build]"
@@ -21,8 +22,7 @@ function usage {
     echo "  --force_spliceSE                 Not recommended: If 'S' in tests, single-end reads are run with splicing STAR."
     echo "  --force_fusionSE                 Not recommended: If 'f' in tests, single-end reads are run with STAR-fusion."
     echo "  --synapseID            synID     Parent of desired file directory."
-    echo "  --synapseSpecies       string    If --synapseID is set, specify species. ['human' or 'mouse] Default: 'human'"
-    echo "  --synapseMergeFile     file      Mapping from downloaded files to sample names [required for synapse fastqs]."                
+    echo "  --synapseIDList        file      File with newline-separated list of synpaseIDs (samples or sample folders)."               
     echo "  --username             string    Synapse username for downloading data (if --synapse is specified)."
     echo "  --help                           Display usage info"
     echo
@@ -33,8 +33,8 @@ function usage {
     echo "  Running salmon and splicing STAR on runs listed in SRP045672 with fastp filtering/trimming:" 
     echo "  SRA_RNASeq_Pipeline -a SRP045672 -p sraTest/ -t sS -P 80 --fastp "
     echo
-    echo "  Running all tests on a folder of mouse fastq files identified by the synapse ID syn123456:"
-    echo "  SRA_RNASeq_Pipeline -s mouse -p synapseTest/ --synapse --synapseID=syn123456 --synapseMergeFile=synMerge.txt --username=uName12 --python27_env=python27Env --SF_env=STAR270Env"
+    echo "  Running all tests on a folder of fastq files identified by the synapse ID syn123456:"
+    echo "  SRA_RNASeq_Pipeline -p synapseTest/ --synapseID=syn123456 --username=uName12 --python27_env=python27Env --SF_env=STAR270Env"
     echo
     exit 1
 }
@@ -50,6 +50,7 @@ source $CONDA_PREFIX/etc/profile.d/conda.sh
 while [ "$#" -gt 0 ]; do
   case "$1" in
     -a) ACC="$2"; shift 2;;
+    -l) ACCLST="$2"; shift 2;;    
     -p) PROJECT_DIR="$2"; shift 2;;
     -t) TESTS="$2"; shift 2;;
     -g) GENOME_DIR_TOP="$2"; shift 2;;
@@ -57,6 +58,7 @@ while [ "$#" -gt 0 ]; do
     -c) CONDAENV="$2"; shift 2;;
     
     --SRP_accession=*) ACC="${1#*=}"; shift 1;;
+    --SRA_list=*) ACCLST="${1#*=}"; shift 1;;        
     --project_dir=*) PROJECT_DIR="${1#*=}"; shift 1;;
     --tests=*) TESTS="${1#*=}"; shift 1;;
     --genome_dir=*) GENOME_DIR_TOP="${1#*=}"; shift 1;;
@@ -67,8 +69,7 @@ while [ "$#" -gt 0 ]; do
     --force_fusionSE) FSF="${1#*=}"; shift 1;;
     --fastp) FP="${1#*=}"; shift 1;;
     --synapseID=*) SYNID="${1#*=}"; shift 1;;
-    --synapseSpecies=*) synapseSpecies="${1#*=}"; shift 1;;
-    --synapseMergeFile=*) synapseMergeFile="${1#*=}"; shift 1;;            
+    --synapseIDList=*) SYNLST="${1#*=}"; shift 1;;         
     --username=*) USERR="${1#*=}"; shift 1;;
     --help) HELP="${1#*=}"; shift 1;;
 
@@ -84,7 +85,7 @@ if [ ! -z "$HELP" ]; then
 fi
 
 if [ ! -z "$SYNID" ]; then
-  SPECIES=${synapseSpecies:="human"} 
+  #SPECIES=${synapseSpecies:="human"} 
   if [ -z "$USERR" ]; then
     echo "ERROR: To run synapse, you must specify your synapse user name."
     usage
@@ -94,17 +95,21 @@ if [ ! -z "$SYNID" ]; then
   echo -n Password: 
   read -s PASS
   echo
-  
 elif [ -z "$ACC" ]; then
-  usage
-  exit 1  
-
+  if [ -z "$ACCLST" ]; then
+    usage
+    exit 1  
+  fi
 fi
-
+if [ ! -z "$ACCLST" ]; then
+    echo "Acquiring sample info will take longer with list input method depending on list size ... "
+fi  
 
 # Set defaults for variables not supplied
 
 THREADS=${THREADS:=1}
+ACCLST=${ACCLST:="none"}
+ACC=${ACC:="none"}
 TESTS=${TESTS:="stSf"}
 GENOME_DIR_TOP=${GENOME_DIR_TOP:=$SCRIPT_DIR/genome_build}
 if [ ! -d $GENOME_DIR_TOP ]; then
@@ -160,45 +165,31 @@ fi
 ) &>/dev/null
 
 if [ ! -z "$SYNID" ]; then
-  # Get the synapse to filename mapping
-  python $SCRIPT_DIR/getSynapse.py $SYNID $USERR $PASS Code/
-  if [ ! -z "$synapseMergeFile" ]; then
-    dos2unix $synapseMergeFile &>/dev/null
-  fi
-  fileType=$(Rscript $SCRIPT_DIR/checkExtension_Synapse.R)
-  #cat $RUN_INFO > Code/runInfo_Table.txt 
-  # Save a copy in the code dir
-  RUN_INFO=Code/synapse.csv
-  cat $RUN_INFO | tr -s '\t' ',' | csvcut -c synID > Code/Accession_List.txt
+  SYNLST=${SYNLST:="none"}
+  RUN_INFO=$(Rscript $SCRIPT_DIR/get_SYN_info.R $SYNID $SYNLST $SCRIPT_DIR)
+  echo $RUN_INFO  
+  fileType=$(Rscript $SCRIPT_DIR/checkExtension_Synapse.R $RUN_INFO)
+  echo $fileType
 else
   # Isolate the runList and convert to table
-  RES=0
-  while [ ! $RES -eq 1 ]
-  do
-    RES=$(Rscript $SCRIPT_DIR/get_SRA_info.R $ACC $PROJECT_DIR) # Get Runinfo table and save a copy in the code dir
-    if [ $RES == 'err' ]; then
-      echo "ERROR: No RNA-Seq data found for $ACC. Double-check your input and please contact package author if this appears to be a bug."
-      usage
-      exit 1
-    fi
-  done 
-  
-  #cat $RUN_INFO > Code/runInfo_Table.txt 
-  # Save a copy in the code dir
-  RUN_INFO=Code/runInfo_Table.txt
-  cat $RUN_INFO | tr -s '\t' ',' | csvcut -c Run > Code/Accession_List.txt
+  RUN_INFO=$(Rscript $SCRIPT_DIR/get_SRA_info.R $ACC $ACCLST) # Get Runinfo table and save a copy in the code dir
 fi
-
+echo "Finished processing runInfo table... output stored in "$RUN_INFO # Prints success or failure message     
+# Save a copy in the code dir
+ACCNAME=$(basename $RUN_INFO .txt)
+cat $RUN_INFO | tr -s '\t' ',' | csvcut -c Run > Code/$ACCNAME.accessionList.txt
+LOGFILE=Code/$ACCNAME.pipeLineLog.txt
+ACCLISTRUN=Code/$ACCNAME.accessionList.txt
 
 
 ### MAIN PIPELINE ###
 
 #Output stderr to a log file
-LOGFILE=Code/pipeLineLog.txt
-
 (
   echo "$(date "+%m%d%Y %T") : Starting main pipline ... "
-      
+  echo
+  echo "Run info table for accessions is: "$RUN_INFO
+  echo "Run access list is: "$ACCLISTRUN
   # This is needed for STAR later
   ulimit -n 10000   
     
@@ -216,13 +207,13 @@ LOGFILE=Code/pipeLineLog.txt
     if [ -z $SYNID ]; then 
       echo
       echo "SRR Accession: "$line  
-      echo
-      SPECIES=$(Rscript $SCRIPT_DIR/getSpeciesSRA.R $line)
-      echo $SPECIES
+      SPECIES=$(Rscript $SCRIPT_DIR/getSpeciesSRA.R $line $RUN_INFO )
       if [ ! "$SPECIES" == "human" ] && [ ! "$SPECIES" == "mouse" ]; then
         echo "WARNING: species for " $line " is an unrecognized type: '"$SPECIES"'. Skipping this accession ... "
         continue
       fi
+      echo "Detected species: "$SPECIES
+      echo
       GENOME_DIR=$GENOME_DIR_TOP/$SPECIES
       if [ ! -d $GENOME_DIR ]; then
         echo "ERROR: $SPECIES genome subdir not found -- exiting"
@@ -266,36 +257,37 @@ LOGFILE=Code/pipeLineLog.txt
           fi
         fi
       else
-        echo "WARNING: "$line"_1.fastq already exists ... skipping this sample ... "
-        continue
+        echo $line"_1.fastq already exists ... proceeding with pipeline ... "
       fi
     else 
       if [ $line == "synID" ]; then
         continue
       fi
+      # Get species info
+      echo
+      echo "Synapse Accession: "$line  
+      SPECIES=$(Rscript $SCRIPT_DIR/getSpeciesSYN.R $line $RUN_INFO )
+      if [ ! "$SPECIES" == "human" ] && [ ! "$SPECIES" == "mouse" ]; then
+        echo "WARNING: species for " $line " is an unrecognized type: '"$SPECIES"'. Skipping this accession ... "
+        continue
+      fi
+      echo "Detected species: "$SPECIES
+      echo
+      GENOME_DIR=$GENOME_DIR_TOP/$SPECIES
+      if [ ! -d $GENOME_DIR ]; then
+        echo "ERROR: $SPECIES genome subdir not found -- exiting"
+        exit 1
+      fi
+
+      
       synapse login -u $USERR -p $PASS --rememberMe
       mkdir Data/Raw_Reads/synDownloadTmp
       if [ $fileType == "fastq" ]; then
         echo "FASTQ file input ... "
-        if [ -z "$synapseMergeFile" ]; then
-          echo
-          echo "ERROR: File type is fastq, but no synapseMergeFile is provided. This is required to handle mate pairs, file renaming, and technical replicates. The synapseMergeFile is a TSV in which the first column contains the fastq file names and the second contains corresponding sample names, patient IDs, etc, to which the file belongs. For example:" 
-          echo
-          echo "GHX9293.1.fastq.gz  patient0098_TCX"
-          echo "GHX9293.2.fastq.gz  patient0098_TCX"
-          echo
-          echo "or... in the case of technical replicates:"
-          echo
-          echo "AGTGCA_np099848_GTCACT_01_01.fastq  20092_G"
-          echo "AGTGCA_np099848_GTCACT_02_01.fastq  20092_G"
-          echo "AGTGCA_np099848_GTCACT_01_02.fastq  20092_G"
-          echo "AGTGCA_np099848_GTCACT_02_02.fastq  20092_G"
-          echo
-          exit 1
-        fi
+        
         
         echo "Downloading fastq files and merging any technical replicates ... "
-        techReps=$(Rscript $SCRIPT_DIR/techReps_Synapse.R $line $synapseMergeFile) # Checks for pre-existing files internally
+        techReps=$(Rscript $SCRIPT_DIR/techReps_Synapse.R $line $RUN_INFO) # Checks for pre-existing files internally
         
         if [ "$techReps" != "no" ]; then
           if [ "$techReps" == "skip" ]; then
@@ -542,7 +534,7 @@ LOGFILE=Code/pipeLineLog.txt
       rm Data/Raw_Reads/$line"_1.fastq"
     fi
     
-  done < Code/Accession_List.txt
+  done < $ACCLISTRUN
   wait
   
   echo "$(date "+%m%d%Y %T") : Done"
